# Generated by Django 2.2.3 on 2019-07-29 21:20

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=15)),
                ('asset', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=None)),
                ('costs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('number_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('id_external', models.CharField(max_length=100)),
                ('id_rarity', models.CharField(choices=[('8e5193a9321cb28ef234ee245d80806304e7a5dd', 'Common'), ('294e1081bbca34e3001ab450b7bf15197c2dfe6d', 'Unccommon'), ('7139e95f14384725d05b0dfa5798d83028d134be', 'Rare'), ('74387df0cc25a62b5970d9abc11b78ef53506e90', 'Mythic Rare'), ('0df13ac5f3ba122c61db582141a6947ca01f038d', 'Special'), ('ba59208cd4db89b4fe1faa81aa6206fc0f1408cf', 'Land'), ('28970c2833085a4b2eb3c2a232a6f0acc07240e4', 'Promo'), ('fc8f09a03c03b14b68c08c06b0f5a3111ccdac89', 'Bonus')], max_length=40)),
                ('id_set', models.CharField(max_length=40)),
                ('id_asset', models.CharField(max_length=40)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('rate_votes', models.DecimalField(decimal_places=0, max_digits=10)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), size=None)),
                ('order_external', models.CharField(max_length=15)),
                ('artist', models.CharField(max_length=255)),
                ('flavor', models.TextField(max_length=1024)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Set')),
            ],
        ),
    ]
